services:
  - type: web
    name: vidai-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --timeout 7200
    envVars:
      - key: PEXELS_API_KEY
        sync: false
      - key: R2_ENDPOINT
        sync: false
      - key: R2_ACCESS_KEY
        sync: false
      - key: R2_SECRET_KEY
        sync: false
      - key: R2_BUCKET
        sync: false
      - key: R2_PUBLIC_URL
        sync: false
      - key: OLLAMA_MODEL
        value: mistral
